baseURL: https://workdojos.com
languageCode: en-us
title: Work Dojos
theme: hugo-fresh
googleAnalytics:: G-M8MTX31YJH
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
      hardWraps: true

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Open a dojo.  In whatever it is that you do.  We will help you do you, digitally.
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/workdojos_logo_small_2.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Dashboard. Dojo.  Business in a Box.
    # Hero subtitle (optional)
    subtitle: Ditch your dependency on Big Tech.  Join the open-source revolution.  Build your own kingdom on your own server. 
    # Button text
    buttontext: Get a dojo
    # Where the main hero button links to
    buttonlink: "https://workdojos.com/marketplace"
    # Hero image (from static/images/___)
    image: logos/inspire.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    


  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /features
    sublinks:
    - title: Your own website
      url: /features/website
    - title: Your own chat app
      url: /features/chat
    - title: Your own blogging engine
      url: /features/blog
    - title: Your own automation app
      url: /features/automation
    - title: Your own VoIP number
      url: /features/voip
    - title: Your own database app
      url: /features/db
    - title: Your own password manager
      url: /features/passwords
    - title: Your own virtual cafe
      url: /features/virtualcafe
    - title: Your own wiki
      url: /features/wiki

  - title: Pricing
    url: https://blog.workdojos.com/#/portal/signup
  

  - title: Featured dojos
    sublinks:
    - title: Administrator Dojo
      url: https://workdojos.com/administrators
    - title: App Developer Dojo
      url: https://workdojos.com/appdeveloper
    - title: Biologist Dojo
      url: https://workdojos.com/biologist
    - title: Clinician Dojo
      url: https://workdojos.com/clinician
    - title: Exporter Dojo
      url: https://workdojos.com/exporter
    - title: Firefighter Dojo
      url: https://workdojos.com/firefighters
    - title: Grower Dojo
      url: https://workdojos.com/growers
    - title: Interpreter Dojo
      url: https://workdojos.com/interpreters
    - title: Law Enforcement Dojo
      url: https://workdojos.com/lawenforcement
    - title: Life Coach Dojo
      url: https://workdojos.com/lifecoaches
    - title: Lyricist Dojo
      url: https://workdojos.com/lyricist
    - title: Novelist Dojo
      url: https://workdojos.com/novelist
    - title: Metaversial Dojo
      url: https://workdojos.com/metaversial
    - title: Musician Dojo
      url: https://workdojos.com/musicalartist
    - title: Non-Profit Dojo
      url: https://workdojos.com/non-profit
    - title: Novelist Dojo
      url: https://workdojos.com/novelist
    - title: Philosopher Dojo
      url: https://workdojos.com/philosophers
    - title: Physicist Dojo
      url: https://workdojos.com/physicist
    - title: Project Manager Dojo
      url: https://workdojos.com/projectmanagers
    - title: Researcher Dojo
      url: https://workdojos.com/researchers
    - title: Retailer Dojo
      url: https://workdojos.com/retailers
    - title: School Teacher Dojo
      url: https://workdojos.com/schoolteachers
    - title: Social Worker Dojo
      url: https://workdojos.com/socialworker
    - title: Thespian Dojo
      url: https://workdojos.com/thespian
    - title: Gamer Dojo
      url: https://workdojos.com/videogamers
    - title: Yogi Dojo
      url: https://workdojos.com/yogainstructor
  - title: Log in
    url: https://blog.workdojos.com/#/portal/login
  - title: Sign up
    url: https://blog.workdojos.com/#/portal/signup
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: workdojos_logo_small_2
    sections:



    - title: Browse dojos
      icon: image
      links:
      - text: AccountExecutive
        url: https://workdojos.com/AccountExecutive
      - text: Actuaries
        url: https://workdojos.com/Actuaries
      - text: Administrators
        url: https://workdojos.com/Administrators
      - text: Adventurers
        url: https://workdojos.com/Adventurers
      - text: Agriculturist
        url: https://workdojos.com/Agriculturist
      - text: Animators
        url: https://workdojos.com/Animators
      - text: AppDeveloper
        url: https://workdojos.com/AppDeveloper
      - text: ArmchairExpert
        url: https://workdojos.com/ArmchairExpert
      - text: Aviationist
        url: https://workdojos.com/Aviationist
      - text: Bankroller
        url: https://workdojos.com/Bankroller
      - text: Baristas
        url: https://workdojos.com/Baristas
      - text: Bartenders
        url: https://workdojos.com/Bartenders
      - text: Beauticians
        url: https://workdojos.com/Beauticians
      - text: BeerGarden
        url: https://workdojos.com/BeerGarden
      - text: Biologist
        url: https://workdojos.com/Biologist
      - text: Botanist
        url: https://workdojos.com/Botanist
      - text: BrewMasters
        url: https://workdojos.com/BrewMasters
      - text: Captains
        url: https://workdojos.com/Captains
      - text: Curators
        url: https://workdojos.com/Curators
      - text: DigitalMarketers
        url: https://workdojos.com/DigitalMarketers
      - text: Economists
        url: https://workdojos.com/Economists
      - text: Evangelist
        url: https://workdojos.com/Evangelist
      - text: EventPlanners
        url: https://workdojos.com/EventPlanners
      - text: ExecutiveSearch
        url: https://workdojos.com/ExecutiveSearch
      - text: Exhibitionist
        url: https://workdojos.com/Exhibitionist
      - text: Expatriate
        url: https://workdojos.com/Expatriate
      - text: Explorers
        url: https://workdojos.com/Explorers
      - text: Exporter
        url: https://workdojos.com/Exporter
      - text: Facilitator
        url: https://workdojos.com/Facilitator
      - text: Financier
        url: https://workdojos.com/Financier
      - text: Firefighters
        url: https://workdojos.com/Firefighters
      - text: Franchiser
        url: https://workdojos.com/Franchiser
      - text: Geneticist
        url: https://workdojos.com/Geneticist
      - text: Ghostwriters
        url: https://workdojos.com/Ghostwriters
      - text: GraphicDesigner
        url: https://workdojos.com/GraphicDesigner
      - text: Growers
        url: https://workdojos.com/Growers
      - text: Healers
        url: https://workdojos.com/Healers
      - text: Importer
        url: https://workdojos.com/Importer
      - text: Interpreters
        url: https://workdojos.com/Interpreters
      - text: Investigators
        url: https://workdojos.com/Investigators
      - text: InvestmentBanker
        url: https://workdojos.com/InvestmentBanker
      - text: Jeweler
        url: https://workdojos.com/Jeweler
      - text: JobSeeker
        url: https://workdojos.com/JobSeeker
      - text: Labtech
        url: https://workdojos.com/Labtech
      - text: Landowners
        url: https://workdojos.com/Landowners
      - text: LawEnforcement
        url: https://workdojos.com/LawEnforcement
      - text: LeadGenerator
        url: https://workdojos.com/LeadGenerator
      - text: Legislator
        url: https://workdojos.com/Legislator
      - text: Liaison
        url: https://workdojos.com/Liaison
      - text: Librarian
        url: https://workdojos.com/Librarian
      - text: LifeCoaches
        url: https://workdojos.com/LifeCoaches
      - text: Lighthouses
        url: https://workdojos.com/Lighthouses
      - text: Litigator
        url: https://workdojos.com/Litigator
      - text: Logistician
        url: https://workdojos.com/Logistician
      - text: Lyricist
        url: https://workdojos.com/Lyricist
      - text: Machinist
        url: https://workdojos.com/Machinist
      - text: Manufacturers
        url: https://workdojos.com/Manufacturers
      - text: MediaBuyer
        url: https://workdojos.com/MediaBuyer
      - text: Metaversial
        url: https://workdojos.com/Metaversial
      - text: MortgageBrokers
        url: https://workdojos.com/MortgageBrokers
      - text: Motivators
        url: https://workdojos.com/Motivators
      - text: MusicAlartist
        url: https://workdojos.com/MusicAlartist
      - text: Negotiator
        url: https://workdojos.com/Negotiator
      - text: Neurologists
        url: https://workdojos.com/Neurologists
      - text: Non-Profit
        url: https://workdojos.com/Non-Profit
      - text: Novelist
        url: https://workdojos.com/Novelist
      - text: Operatives
        url: https://workdojos.com/Operatives
      - text: ParkRanger
        url: https://workdojos.com/ParkRanger
      - text: Pathologist
        url: https://workdojos.com/Pathologist
      - text: Pharmacists
        url: https://workdojos.com/Pharmacists
      - text: Philosophers
        url: https://workdojos.com/Philosophers
      - text: PhotoJournalist
      - text: PhysicalTherapist
        url: https://workdojos.com/PhysicalTherapist
      - text: Physicist
        url: https://workdojos.com/Physicist
      - text: Playwright
        url: https://workdojos.com/Playwright
      - text: Politician
        url: https://workdojos.com/Politician
      - text: Practitioner
        url: https://workdojos.com/Practitioner
      - text: ProjectManagers
        url: https://workdojos.com/ProjectManagers
      - text: PublicRelations
        url: https://workdojos.com/PublicRelations
      - text: Racers
        url: https://workdojos.com/Racers
      - text: RegisteredNurse
        url: https://workdojos.com/RegisteredNurse
      - text: RemoteWorker
        url: https://workdojos.com/RemoteWorker
      - text: Researchers
        url: https://workdojos.com/Researchers
      - text: Retailers
        url: https://workdojos.com/Retailers
      - text: SalesCoaches
        url: https://workdojos.com/SalesCoaches
      - text: Schoolmates
        url: https://workdojos.com/Schoolmates
      - text: SchoolTeachers
        url: https://workdojos.com/SchoolTeachers
      - text: Screenwriter
        url: https://workdojos.com/Screenwriter
      - text: SocialWorker
        url: https://workdojos.com/SocialWorker
      - text: Sociologist
        url: https://workdojos.com/Sociologist
      - text: SpiritualCoach
        url: https://workdojos.com/SpiritualCoach
      - text: Statistician
        url: https://workdojos.com/Statistician
      - text: Strategists
        url: https://workdojos.com/Strategists
      - text: System Administrators
        url: https://workdojos.com/Admins
      - text: Telemarketer
        url: https://workdojos.com/Telemarketer
      - text: Theologian
        url: https://workdojos.com/Theologian
      - text: Thespian
        url: https://workdojos.com/Thespian
      - text: TownSquare
        url: https://workdojos.com/TownSquare
      - text: TravelAgents
        url: https://workdojos.com/TravelAgents
      - text: Travelers
        url: https://workdojos.com/Travelers
      - text: Trustees
        url: https://workdojos.com/Trustees
      - text: Unions
        url: https://workdojos.com/Unions
      - text: VideoGamers
        url: https://workdojos.com/VideoGamers
      - text: WebDesigners
        url: https://workdojos.com/WebDesigners
      - text: WebJedi
        url: https://workdojos.com/WebJedi
      - text: WeekendWarrior
        url: https://workdojos.com/WeekendWarrior
      - text: Wholesalers
        url: https://workdojos.com/Wholesalers
      - text: Wingman
        url: https://workdojos.com/Wingman
      - text: Wordsmith
        url: https://workdojos.com/Wordsmith
      - text: Workmates
        url: https://workmates.live
      - text: YogaInstructor
        url: https://workdojos.com/YogaInstructor
      - text: Zookeeper
        url: https://workdojos.com/Zookeeper
    - title: Around the world
      icon: globe
      links:
      - text: **coming soon**
        url: https://workdojos.com/afghanistan

    - title: E-mail us
      icon: envelope
      links:
      - text: Our founder
        url: mailto:workdojos@gmail.com
      - text: Technical support
        url: mailto:workmates.live@gmail.com
      - text: Investors
        url: mailto:workmates.live@outlook.com
      - text: HR
        url: mailto:workmates.live@outlook.com


    - title: Chat now
      icon: user
      links:
      - text: Our admins
        url: https://chat.workmates.live/channel/Admins
      - text: Our founders
        url: https://chat.workmates.live/channel/Cofounder
      - text: Technical support
        url: https://chat.workmates.live/channel/support
      - text: Recruiting
        url: https://chat.workmates.live/channel/Jobseeker

  section1:
    title: Every dojo starts with a dashboard.
    subtitle: And that's just the beginning.
    tiles:
    - title: A dashboard to rule them all.
      icon: mouse-globe
      text: Because it's ALL yours (including your own domain)      
      url: https://admins.workdojos.com
      buttonText: See it live
    - title: Your kingdom front and center.  
      icon: laptop-cloud
      text: Set your browser's start page to it.  An uncluttered space for you and your apps.
      url: https://workdojos.com/ghost
      buttonText: See apps
    - title: Self-hosting's never been easier.
      icon: plug-cloud
      text: Experience the thrill of being the almighty ADMIN!
      url: https://blog.workdojos.com/#/portal/signup
      buttonText: Free trial

  section2:
    title: The ultimate sandbox.
    subtitle: A gateway to everything open-source.
    features:
    - title: Your server, your data.
      text: For as little as $8/month you can create an entire digital ecosystem for yourself, your passions, projects, and people.
      icon: plug-cloud
    - title: Dojo.
      text: “The place of the way” in Japanese. An honored place for deliberate practice and building things.  The ultimate sandbox.
      icon: laptop-cloud
    - title: To be dependent on Big Tech is to be at a disadvantage.
      text: Prepare for the digital future AND save money.  $100/month in value and utility for as little as $8/month.  
      icon: mobile-feed
    - title: Build the next big thing.
      text: With millions of open-source apps and micro-services at your beck and call, you CAN build the next big thing!
      icon: mouse-globe


  section3:
    title: Pick a path.
    subtitle: Choose from over 1000 areas of expertise or blaze your own trail.
    image: logos/undraw_road_to_knowledge_m8s0.svg
    buttonText: Browse dojos
    buttonLink: "https://workdojos.com/marketplace"
  section4:
    title: Our mission.
    subtitle: To make open-source more accessible.
    clients:
    - name: Sean
      quote: I never thought I could host my own server.  I didn't even know what "self-hosting" meant (I do now ... and it's changed everything). Dojos showed me the way and it's been a fun ride!
      job: Social Media Marketer
      img: 3
    - name: John
      quote: Linux used to freak me out.  Now I kind of like it.  Even as a non-dev I can make it do what I want (kinda sorta, but sometime's that's just enough!).  Most of the time I don't have to do anything, it's all pretty plug 'n play and very user-friendly (and cost-friendly) overall.  
      job: Graphic Designer
      img: 2
    - name: Jessi
      quote: We saved a ton of money over expensive SaaS apps (and predatory webhost pricing that goes way up after the first year) by simply going open-source.  We deployed a whopping 20 websites in a single dojo with space left over for more, as well as a chat app and company wiki.  Our teams also like the autonomy they get by having their own private dojos.
      job: HR Manager
      img: 1
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: workdojos_logo_small_2.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:

      # Icons are from Font Awesome
      
    - link: https://www.instagram.com/workmateslive/
      icon: instagram
    - link: https://www.pinterest.com/workmateslive/
      icon: pinterest
    - link: https://twitter.com/workdojos
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Features
          link: /features
        - text: Partners
          link: /partners
        - text: Why choose us?
          link: /why
        - text: Free trial
          link: https://blog.workdojos.com/#/portal/signup
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /docs/start
        - text: Compare pricing
          link: https://workdojos.com/ghost/
        - text: Privacy policy
          link: /docs/privacy
        - text: Built with Hugo
          link: https://gohugo.io/             
      column3:
        title: "Company"
        links:
        - text: Blog
          link: https://blog.workdojos.com
        - text: Pitch
          link: https://workdojos.com/pitch
        - text: Investors
          link: https://workdojos.com/pitch
        - text: Get involved
          link: https://workdojos.com/get-involved

