baseURL: https://workdojos.com
languageCode: en-us
title: Dojos
theme: hugo-fresh
disablePathToLower: true
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
      hardWraps: true


params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Free and open-source technology for all.
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/workmates logo NEW NEW red green.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Build anything.
    # Hero subtitle (optional)
    subtitle: With free and open-source technology. 
    # Button text
    buttontext: Browse
    # Where the main hero button links to
    buttonlink: "https://www.workdojos.com/marketplace/"
    hrefTargetBlank: true
    # Hero image (from static/images/___)
    image: logos/flick3.gif
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    


  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About
    url: https://about.workdojos.com
  - title: Dashboards
    url: https://dashboards.workdojos.com


  - title: Featured
    sublinks:
    - title: Administrator Dojo
      url: https://dashboards.workdojos.com/#Administrators
    - title: Biologist Dojo
      url: https://dashboards.workdojos.com/#Biologist
    - title: Clinician Dojo
      url: https://dashboards.workdojos.com/#Doctors
    - title: Firefighter Dojo
      url: https://dashboards.workdojos.com/#Firefighters
    - title: Grower Dojo
      url: https://dashboards.workdojos.com/#Growers
    - title: Interpreter Dojo
      url: https://dashboards.workdojos.com/#Interpreters
    - title: Life Coach Dojo
      url: https://dashboards.workdojos.com/#Life-Coaches
    - title: Lyricist Dojo
      url: https://dashboards.workdojos.com/#Lyricist
    - title: Novelist Dojo
      url: https://dashboards.workdojos.com/#Novelist
    - title: Musician Dojo
      url: https://dashboards.workdojos.com/#Musical-Artists
    - title: Novelist Dojo
      url: https://dashboards.workdojos.com/#Novelist
    - title: Philosopher Dojo
      url: https://dashboards.workdojos.com/#Philosophers
    - title: Physicist Dojo
      url: https://dashboards.workdojos.com/#Physicist
    - title: Teacher Dojo
      url: https://dashboards.workdojos.com/#School-Teachers
    - title: Social Worker Dojo
      url: https://dashboards.workdojos.com/#Social-Workers
    - title: Thespian Dojo
      url: https://dashboards.workdojos.com/#Thespian


  - title: Pricing
    url: https://blog.workdojos.com/#/portal/signup
  - title: Sign up
    url: https://blog.workdojos.com/#/portal/signup
    button: true

  sectionpoop:
    title: Unlock everything open-source.
    subtitle: Become the almighty Admin!  

  section1:
    title: Free dashboards.
    subtitle: An uncluttered ad-free space for anything you want.

  sectionZb:
    title: Free chat apps.
    subtitle: Sign up to learn how to create your own chat server.

  section1Z:
    title: Free educational tools.
    subtitle: Parents and teachers, spin up learning management systems on-the-fly!

#  sectionZc:
   # title: Free templates.
   # subtitle: Sign up to get a free guide to self-hosting.

  sectionZd:
    title: Free landing pages.
    subtitle: Sign up to get a free landing page built in React.

  sectionZe:
    title: Pick a path.
    subtitle: Choose from below or blaze your own trail!
    image: logos/workmates.png

#  section3:
#    title: Pick a path.
#    subtitle: Choose from over 100 pre-built dojos or blaze your own trail.
#    image: logos/workmates.png
#    buttonText: Browse all
#    buttonLink: "https://workmates.live/marketplace"

  section3a:
    title: Free and Open-Source AI.
    subtitle: Featuring a cast of 16 AI avatars made exclusively with open-souce technology.
    image: logos/multisad bigger.gif
    buttonText: Go to Youtube
    buttonLink: "https://youtube.com/@dojofans"

    
  
  section5: false
  
  footer:
    # Logo (from /images/logos/___)
    logo: workmates logo NEW NEW red green.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:

      # Icons are from Font Awesome
    - link: https://github.com/workdojos
      icon: github
    - link: https://twitter.com/workdojos
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Free trial
          link: https://blog.workdojos.com/#/portal/signup
        - text: 60-Day Challenge
          link: https://blog.workdojos.com/#/portal/signup
        - text: Dashboards
          link: https://dashboards.workdojos.com
        - text: Pricing
          link: https://blog.workdojos.com/#/portal/signup
      column2:
        title: "Docs"
        links:
        - text: Awesome-Selfhosted
          link: https://github.com/awesome-selfhosted/awesome-selfhosted
        - text: Privacy policy
          link: /docs/privacy
        - text: Built with Hugo
          link: https://gohugo.io/             
      column3:
        title: "Company"
        links:
        - text: About
          link: https://about.workdojos.com
        - text: Blog
          link: https://blog.workdojos.com
        - text: Chat Now
          link: https://chat.workmates.live/channel/support

