baseURL: https://workdojos.com
languageCode: en-us
title: WorkDojos
theme: hugo-fresh
disablePathToLower: true
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
      hardWraps: true


params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Free and open-source technology for all.
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/workmates logo NEW NEW red green.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Build a business.
    # Hero subtitle (optional)
    subtitle: With free and open-source technology. 
    # Button text
    buttontext: Browse all
    # Where the main hero button links to
    buttonlink: "https://workmates.live/marketplace"
    hrefTargetBlank: true
    # Hero image (from static/images/___)
    image: logos/flick3.gif
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    


  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:



  - title: Features
    url: /features
    sublinks:
    - title: Your own website
      url: /features/website
    - title: Your own chat app
      url: /features/chat
    - title: Your own blogging engine
      url: /features/blog
    - title: Your own automation app
      url: /features/automation
    - title: Your own database app
      url: /features/db
    - title: Your own password manager
      url: /features/passwords
    - title: Your own virtual cafe
      url: /features/virtualcafe
    - title: Your own wiki
      url: /features/wiki


  - title: Featured
    sublinks:
    - title: Administrator Dojo
      url: https://workdojos.com/administrators
    - title: Biologist Dojo
      url: https://workdojos.com/biologist
    - title: Clinician Dojo
      url: https://workdojos.com/clinician
    - title: Firefighter Dojo
      url: https://workdojos.com/firefighters
    - title: Grower Dojo
      url: https://workdojos.com/growers
    - title: Interpreter Dojo
      url: https://workdojos.com/interpreters
    - title: Life Coach Dojo
      url: https://workdojos.com/lifecoaches
    - title: Lyricist Dojo
      url: https://workdojos.com/lyricist
    - title: Novelist Dojo
      url: https://workdojos.com/novelist
    - title: Musician Dojo
      url: https://workdojos.com/musicalartist
    - title: Novelist Dojo
      url: https://workdojos.com/novelist
    - title: Philosopher Dojo
      url: https://workdojos.com/philosophers
    - title: Physicist Dojo
      url: https://workdojos.com/physicist
    - title: Teacher Dojo
      url: https://workdojos.com/schoolteachers
    - title: Social Worker Dojo
      url: https://workdojos.com/socialworker
    - title: Thespian Dojo
      url: https://workdojos.com/thespian
  - title: Pricing
    url: https://blog.workdojos.com/#/portal/signup
  - title: Log in
    url: https://blog.workdojos.com/#/portal/login
  - title: Sign up
    url: https://blog.workdojos.com/#/portal/signup
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: workmates logo NEW NEW red green
    sections:



    - title: Browse
      icon: image
      links:
      - text: AccountExecutive
        url: https://workdojos.com/AccountExecutive
      - text: Administrators
        url: https://workdojos.com/Administrators
      - text: Agriculturist
        url: https://workdojos.com/Agriculturist
      - text: Animators
        url: https://workdojos.com/Animators
      - text: AppDeveloper
        url: https://workdojos.com/AppDeveloper
      - text: Baristas
        url: https://workdojos.com/Baristas
      - text: Bartenders
        url: https://workdojos.com/Bartenders
      - text: Beauticians
        url: https://workdojos.com/Beauticians
      - text: Biologist
        url: https://workdojos.com/Biologist
      - text: Botanist
        url: https://workdojos.com/Botanist
      - text: DigitalMarketers
        url: https://workdojos.com/DigitalMarketers
      - text: Economists
        url: https://workdojos.com/Economists
      - text: EventPlanners
        url: https://workdojos.com/EventPlanners
      - text: Exhibitionist
        url: https://workdojos.com/Exhibitionist
      - text: Explorers
        url: https://workdojos.com/Explorers
      - text: Financier
        url: https://workdojos.com/Financier
      - text: Firefighters
        url: https://workdojos.com/Firefighters
      - text: GraphicDesigner
        url: https://workdojos.com/GraphicDesigner
      - text: Growers
        url: https://workdojos.com/Growers
      - text: Interpreters
        url: https://workdojos.com/Interpreters
      - text: InvestmentBanker
        url: https://workdojos.com/InvestmentBanker
      - text: Jeweler
        url: https://workdojos.com/Jeweler
      - text: Labtech
        url: https://workdojos.com/Labtech
      - text: LawEnforcement
        url: https://workdojos.com/LawEnforcement
      - text: Librarian
        url: https://workdojos.com/Librarian
      - text: LifeCoaches
        url: https://workdojos.com/LifeCoaches
      - text: Litigator
        url: https://workdojos.com/Litigator
      - text: Lyricist
        url: https://workdojos.com/Lyricist
      - text: Machinist
        url: https://workdojos.com/Machinist
      - text: MusicAlartist
        url: https://workdojos.com/MusicAlartist
      - text: Novelist
        url: https://workdojos.com/Novelist
      - text: ParkRanger
        url: https://workdojos.com/ParkRanger
      - text: Philosophers
        url: https://workdojos.com/Philosophers
      - text: PhotoJournalist
      - text: PhysicalTherapist
        url: https://workdojos.com/PhysicalTherapist
      - text: ProjectManagers
        url: https://workdojos.com/ProjectManagers
      - text: RegisteredNurse
        url: https://workdojos.com/RegisteredNurse
      - text: SchoolTeachers
        url: https://workdojos.com/SchoolTeachers
      - text: Screenwriter
        url: https://workdojos.com/Screenwriter
      - text: SocialWorker
        url: https://workdojos.com/SocialWorker
      - text: Statistician
        url: https://workdojos.com/Statistician
      - text: Strategists
        url: https://workdojos.com/Strategists
      - text: Theologian
        url: https://workdojos.com/Theologian
      - text: Thespian
        url: https://workdojos.com/Thespian
      - text: TravelAgents
        url: https://workdojos.com/TravelAgents
      - text: WebDesigners
        url: https://workdojos.com/WebDesigners



    - title: E-mail us
      icon: envelope
      links:
      - text: Our owner
        url: mailto:admin@workdojos.com
      - text: Technical support
        url: mailto:admin@workdojos.com
      - text: Investors
        url: mailto:admin@workdojos.com
      - text: HR
        url: mailto:admin@workdojos.com


    - title: Chat now
      icon: user
      links:
      - text: Our admins
        url: https://chat.workmates.live/channel/Admins
      - text: Our founders
        url: https://chat.workmates.live/channel/Cofounder
      - text: Technical support
        url: https://chat.workmates.live/channel/support
      - text: Recruiting
        url: https://chat.workmates.live/channel/Jobseeker/support




  section1:
    title: Free dashboards.
    subtitle: Sign up to get your own for free.

  section1Z:
    title: For families and teachers.
    subtitle: Spin up a Learning Management System for free!

  sectionZb:
    title: Free chat apps.
    subtitle: Sign up to create a chat server for free.

#  sectionZc:
   # title: Free templates.
   # subtitle: Sign up to get a free guide to self-hosting.

  sectionZd:
    title: Free React apps.
    subtitle: Sign up to get a free landing page built in React.

  sectionZe:
    title: Pick a path.
    subtitle: Choose from below or blaze your own trail.
    image: logos/workmates.png

  section3:
    title: Pick a path.  For any profession.
    subtitle: Choose from over 100 pre-built Dojos or blaze your own trail.
    image: logos/workmates.png
    buttonText: Browse all
    buttonLink: "https://workmates.live/marketplace"

  section3a:
    title: Free and Open-Source AI.
    subtitle: Check out our Youtube channel featuring a cast of 16 AI avatars made exclusively with open-souce technology.
    image: logos/multisad bigger.gif
    buttonText: Go to Youtube
    buttonLink: "https://youtube.com/@dojofans"

    
  
  section5: false
  
  footer:
    # Logo (from /images/logos/___)
    logo: workmates logo NEW NEW red green.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:

      # Icons are from Font Awesome
      
    - link: https://twitter.com/workdojos
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Features
          link: /features
        - text: Partners
          link: /partners
        - text: Free trial
          link: https://blog.workdojos.com/#/portal/signup
        - text: 60-Day Self-Hosting Challenge
          link: https://blog.workdojos.com/#/portal/signup
      column2:
        title: "Docs"
        links:
        - text: Dashboards
          link: https://admins.workdojos.com
        - text: Compare pricing
          link: https://workdojos.com/ghost/
        - text: Privacy policy
          link: /docs/privacy
        - text: Built with Hugo
          link: https://gohugo.io/             
      column3:
        title: "Company"
        links:
        - text: Blog
          link: https://blog.workdojos.com
        - text: About Us
          link: https://blog.workdojos.com/about-us
        - text: Get involved
          link: https://home.workdojos.com/#contact
        - text: Chat Now
          link: https://chat.workmates.live/channel/support

