baseURL: https://workdojos.com
languageCode: en-us
title: Dojos
theme: hugo-fresh
disablePathToLower: true
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
      hardWraps: true


params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Free and open-source technology for all.
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/workmates logo NEW NEW red green.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Build anything.
    # Hero subtitle (optional)
    subtitle: With free and open-source technology. 
    # Button text
    buttontext: Browse
    # Where the main hero button links to
    buttonlink: "https://www.workdojos.com/marketplace/"
    hrefTargetBlank: true
    # Hero image (from static/images/___)
    image: logos/flick3.gif
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    


  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About
    url: https://about.workdojos.com
  - title: Blog
    url: https://blog.workdojos.com
  - title: Dashboards
    url: https://dashboards.workdojos.com


  - title: Featured
    sublinks:
    - title: Administrator Dojo
      url: https://dashboards.workdojos.com/#Administrators
    - title: Biologist Dojo
      url: https://dashboards.workdojos.com/#Biologists
    - title: Clinician Dojo
      url: https://dashboards.workdojos.com/#Doctors
    - title: Firefighter Dojo
      url: https://dashboards.workdojos.com/#Firefighters
    - title: Grower Dojo
      url: https://dashboards.workdojos.com/#Growers
    - title: Interpreter Dojo
      url: https://dashboards.workdojos.com/#Interpreters
    - title: Life Coach Dojo
      url: https://dashboards.workdojos.com/#Life-Coaches
    - title: Lyricist Dojo
      url: https://dashboards.workdojos.com/#Lyricists
    - title: Musician Dojo
      url: https://dashboards.workdojos.com/#Musicians
    - title: Novelist Dojo
      url: https://dashboards.workdojos.com/#Novelists
    - title: Philosopher Dojo
      url: https://dashboards.workdojos.com/#Philosophers
    - title: Physicist Dojo
      url: https://dashboards.workdojos.com/#Physicists
    - title: Teacher Dojo
      url: https://dashboards.workdojos.com/#School-Teachers
    - title: Social Worker Dojo
      url: https://dashboards.workdojos.com/#Social-Workers
    - title: Thespian Dojo
      url: https://dashboards.workdojos.com/#Thespians


  - title: Pricing
    url: https://blog.workdojos.com/#/portal/signup
  - title: Sign up
    url: https://blog.workdojos.com/#/portal/signup
    button: true

  sectionpoop:
    title: Unlock "Open-Source."
    subtitle: Hey Admin!  

  section1:
    title: Free Dashboards.
    subtitle: Uncluttered space for anything you want.

#  sectionZb:
#    title: Personalized Chat Apps.
#    subtitle: Sign up to spin up a private chat server.

#  section1Z:
#    title: Educational Tools.
#    subtitle: Parents and teachers, spin up a learning management system for free!

#  sectionZc:
   # title: Free templates.
   # subtitle: Sign up to get a free guide to self-hosting.

  sectionZd:
    title: Free Templates.
    subtitle: Sign up to get a custom landing page built in React.

  sectionZe:
    title: Pick a path.
    subtitle: Choose from below or blaze your own trail.
    image: logos/workmates.png

#  section3:
#    title: Pick a path.
#    subtitle: Choose from over 100 pre-built dojos or blaze your own trail.
#    image: logos/workmates.png
#    buttonText: Sign up
#    buttonLink: "https://blog.workdojos.com/#/portal/signup"

  section3a:
    title: Open-Source AI.
    subtitle: Meet our cast of 16 characters made with free and open-source AI tech.
    image: logos/multisad bigger.gif
    buttonText: Dojofans
    buttonLink: "https://youtube.com/@dojofans"

    
  
  section5: false
  
  footer:
    # Logo (from /images/logos/___)
    logo: workmates logo NEW NEW red green.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:

      # Icons are from Font Awesome
    - link: https://github.com/workdojos
      icon: github
    - link: https://twitter.com/workdojos
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Free trial
          link: https://blog.workdojos.com/#/portal/signup
        - text: 60-Day Challenge
          link: https://blog.workdojos.com/#/portal/signup
        - text: Dashboards
          link: https://dashboards.workdojos.com
        - text: Pricing
          link: https://blog.workdojos.com/#/portal/signup
      column2:
        title: "Docs"
        links:
        - text: Awesome-Selfhosted
          link: https://github.com/awesome-selfhosted/awesome-selfhosted
        - text: Privacy policy
          link: /docs/privacy
        - text: Built with Hugo
          link: https://gohugo.io/             
      column3:
        title: "Company"
        links:
        - text: About
          link: https://about.workdojos.com
        - text: Blog
          link: https://blog.workdojos.com
        - text: Chat Now
          link: https://chat.workmates.live/channel/support

